name: Docker integration
on:
  push:
    branches: ["main"]

jobs:
  build-and-ship:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Log into docker hub
        uses: docker/login-action@v3
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
        with:
          username: ${{ env.DOCKER_USER_NAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Run Debug
        run: echo "Successfully logged in with $DOCKER_USER_NAME $DOCKER_PASSWORD"

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USER_NAME }}/my-python-app:latest

      - name: Success message
        run: echo "Docker image 'my-python-app:latest' is ready to use"
