name: Docker integration
on:
  push:
    branches: ["main"]

env:
  DOCKER_USER_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-and-ship:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Log into docker hub
        uses: docker/login-action@v3
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
        with:
          username: ${{ env.DOCKER_USER_NAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Run Debug
        run: echo "Successfully logged in with $DOCKER_USER_NAME $DOCKER_PASSWORD"

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USER_NAME }}/my-python-app:${{ matrix.python-version }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}

      - name: Success message
        run: echo "Docker image 'my-python-app:latest' is ready to use"
  
  test-container:
    needs: build-and-ship
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    container: 
      image: ${{ vars.DOCKER_HUB_USERNAME }}/my-python-app:${{ matrix.python-version }}
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    outputs: 
      total_lines: "${{ steps.set_msg.outputs.log_count }}"
    steps:
      # - name: Test container job
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ env.DOCKER_USER_NAME }}
      #     password: ${{ env.DOCKER_PASSWORD }}

      # - name: Pull the image
      #   run: docker pull $DOCKER_USER_NAME/my-python-app:latest

      - name: Run the application script
        # We invoke python directly since we are already inside the container box!
        run: python /app/app.py > test-report.log

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: container-execution-report-${{ matrix.python-version }}
          path: test-report.log

      - name: Calculate metric
        id: set_msg
        run: echo "log_count=$(wc -l < test-report.log)" >> $GITHUB_OUTPUT
  print-metric:
    needs: test-container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps: 
      - name: Show final log metric
        run: |
          echo "Python ${{ matrix.python-version }} execution line count was ${{ needs.test-container.outputs.total_lines }}"


      - name: Broadcast deployment status
        if: github.actor == 'supriyahalyal'
        run: echo "Production metrics validated and verified by project lead."
